[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "events"
version = "2024.18.05"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
kafka-python = ^2.4
