[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "events"
version = "2024.18.05"
readme = "README.md"
requires-python = ">=3.10"

[tool.setuptools]
py-modules = ["event", "kafka_event"]

[scripts]
post_install = 'pip install -r requirements.txt'
